<a href="https://colab.research.google.com/github/yesyifahanimkurniavashti07-hash/BussinesIntelegent/blob/main/Praktik_Preprocessing_Data_(missing_value).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Numpy.Numpy merupakan library pyton yang digunakan untuk KOMPUTASI MATRIKS
2. Matplotlib.pyplot merupakan library phyton untuk PRESENTASI GRAFIK ATAU PLOT
3. Pandas. merupakan library pyhton untuk MENGIMPOR EKSTENSI DATA DARI LUAR (CSV, EXCEL ATAU TEXT).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


1. bagaimana kita bisa membaca dataset .CSV nya?
dengan menuliskan "dataset = pd.read_csv", kemudian kita masukkan variabel x dan y
variabel X, atribut
variabel Y, Label/ class/ keterangan

2. atribut dan label dibagi menjadi 2 variabel, yaitu Atribut (x) dan Label (y)

3. .iloc adalah fungsi untuk memilih (subsetting) baris atau kolom dari sebuah dataset/dataframe berdasarkan posisi indeks numerik(angka), bukan berdasarkan nama label kolom atau barisnya.

4. .values digunakan untuk mengambil data mentah di dalam dataset/dataframe dan mengubahnya menjadi Array Numpy

In [ ]:
dataset = pd.read_csv('/content/Dataset_Missing_Values.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print (x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


1. setelah berhasil menimport data, selanjutnya kita akan mengisikan "Missing Values" =  NAN.
caranya bagaimana?

2. untuk mengisikan missing values kita dapat menggunakan fungction "SIMPLE IMPUTER", untuk memanggil fungction IMPUTER nantinya untuk mengunakan nilai "RATA RATA ATAU MEAN" dari kolomnya menggunakan libary "SKLEARN.IMPUTE" kemudian kita panggil fungctionnya yaitu SIMPLE IMPUTER.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print (x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print (x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)


In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
print (x_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print (x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [ ]:
print (y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print (y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print (x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print (x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
