<a href="https://colab.research.google.com/github/yesyifahanimkurniavashti07-hash/BussinesIntelegent/blob/main/TUGAS_1_BI_YESY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

1. NumPy (np) digunakan untuk melakukan perhitungan angka dan mengolah data dalam bentuk array dengan cepat.
2. Matplotlib (plt) digunakan untuk membuat grafik atau visualisasi, sehingga data lebih mudah dipahami secara visual.
3. Pandas (pd) digunakan untuk membaca, mengolah, dan menganalisis data dalam bentuk tabel seperti file Excel atau CSV.

In [35]:
dataset = pd.read_csv('/content/Dataset_tugas_bi_yesy.csv' , sep=';')
x = dataset.iloc[:, 0:3].values
y = dataset.iloc[:, 3].values

1. dataset = pd.read_csv('/content/Dataset_tugas_bi_yesy.csv', sep=';')
- Kode ini digunakan untuk membaca file dataset dari format CSV.
- pd.read_csv() adalah fungsi dari Pandas untuk membuka file data.
- '/content/Dataset_tugas_bi_yesy.csv' adalah lokasi file (biasanya di Google Colab).
- sep=';' berarti pemisah antar kolom adalah titik koma (;), bukan koma (,).

2. x = dataset.iloc[:, 0:3].values
- Kode ini mengambil data kolom ke-0 sampai ke-2 (3 kolom pertama).
- iloc digunakan untuk mengambil data berdasarkan posisi indeks.
- : artinya ambil semua baris
- 0:3 artinya ambil kolom ke-0, 1, dan 2
- .values mengubah data menjadi array NumPy.

3. y = dataset.iloc[:, 3].values
- Kode ini mengambil kolom ke-3 saja (kolom ke-4).
- Digunakan sebagai target atau label yang ingin diprediksi.

In [52]:
dataset.head()

,Kepala Keluarga,Age,Salary,Purchased
0,Sumari,50.0,100000.0,No
1,Solikun,30.0,NaN,Yes
2,Erqy Ramadhani,25.0,200000.0,No
3,dadang sukadang,40.0,700000.0,No
4,Sony Virawan,21.0,NaN,Yes


Kode dataset.head() digunakan untuk melihat sebagian kecil isi data, biasanya 5 baris pertama. Ini membantu kita mengecek apakah data sudah terbaca dengan benar dan memahami struktur awal dataset sebelum lanjut ke proses berikutnya.

In [36]:
print (x)

[['Sumari' 50.0 100000.0]
 ['Solikun' 30.0 nan]
 ['Erqy Ramadhani' 25.0 200000.0]
 ['dadang sukadang' 40.0 700000.0]
 ['Sony Virawan' 21.0 nan]
 ['Zakaria Muhammad' 24.0 nan]
 ['Valensius Anthony' nan 52000.0]
 ['Lukman Botiah' 48.0 79000.0]
 ['Bahlil ' 50.0 83000.0]
 ['Wowo  bianto' 37.0 67000.0]
 ['Verry Salim' nan 80000.0]
 ['nurrohmin' 22.0 nan]
 ['Fadillah Ghozali' nan 90000.0]
 ['Al' 27.0 60000.0]]


Secara singkat, bagian x berisi data input (fitur), yaitu nama, umur, dan penghasilan dari setiap orang. Terlihat bahwa data sudah berbentuk array, dan ada beberapa nilai yang kosong (nan) yang menandakan data tidak tersedia.

Sedangkan bagian y berisi data target atau label, yaitu keterangan seperti 'Yes' atau 'No'. Data ini biasanya digunakan sebagai hasil yang ingin diprediksi.

In [37]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes']


In [38]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

- SimpleImputer dipanggil untuk membuat alat pengisi data kosong dengan strategi rata-rata (mean).
- imputer.fit(x[:, 1:3]) menghitung nilai rata-rata dari kolom ke-1 sampai ke-2 (biasanya umur dan penghasilan).
- imputer.transform(...) mengganti nilai yang kosong (nan) pada kolom tersebut dengan nilai rata-rata yang sudah dihitung.

In [39]:
print (x)

[['Sumari' 50.0 100000.0]
 ['Solikun' 30.0 151100.0]
 ['Erqy Ramadhani' 25.0 200000.0]
 ['dadang sukadang' 40.0 700000.0]
 ['Sony Virawan' 21.0 151100.0]
 ['Zakaria Muhammad' 24.0 151100.0]
 ['Valensius Anthony' 34.0 52000.0]
 ['Lukman Botiah' 48.0 79000.0]
 ['Bahlil ' 50.0 83000.0]
 ['Wowo  bianto' 37.0 67000.0]
 ['Verry Salim' 34.0 80000.0]
 ['nurrohmin' 22.0 151100.0]
 ['Fadillah Ghozali' 34.0 90000.0]
 ['Al' 27.0 60000.0]]


In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Kode ini digunakan untuk mengubah data kategori (teks) menjadi angka agar bisa diproses oleh model machine learning.
- ColumnTransformer dipakai untuk menentukan kolom mana yang akan diubah,
- OneHotEncoder berfungsi mengubah data kategori (misalnya nama pada kolom pertama) menjadi bentuk angka dalam beberapa kolom biner (0 dan 1).
- ('encoder', OneHotEncoder(sparse_output=False), [0]), artinya kolom ke-0 akan di-encode
- remainder='passthrough' berarti kolom lainnya tetap digunakan tanpa perubahan.
- ct.fit_transform(x) menjalankan proses encoding tersebut, lalu hasilnya diubah menjadi array NumPy.

In [41]:
print (x)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 100000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 30.0 151100.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 25.0 200000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 700000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 21.0 151100.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 24.0 151100.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 34.0 52000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 34.0 80000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 22.0 151100.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 34.0 90000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Kode tersebut digunakan untuk mengubah data label (kategori) menjadi angka.
- LabelEncoder adalah alat dari sklearn yang berfungsi mengonversi data seperti 'Yes' dan 'No' menjadi bentuk numerik, misalnya:
'No' → 0
'Yes' → 1
- Baris le.fit_transform(y) akan membaca semua nilai pada y, menentukan kategorinya, lalu langsung mengubahnya menjadi angka.

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)


Kode tersebut digunakan untuk membagi dataset menjadi data latih dan data uji.
- train_test_split berfungsi memisahkan data menjadi dua bagian:
Data training (x_train, y_train) → digunakan untuk melatih model
Data testing (x_test, y_test) → digunakan untuk menguji performa model
- Parameter test_size = 0.3 berarti 30% data digunakan untuk testing, sedangkan 70% sisanya untuk training.
- random_state = 1 digunakan agar hasil pembagian data tetap sama (konsisten) setiap kali kode dijalankan.

In [44]:
print (y)

[0 1 0 0 1 1 0 1 0 1 0 1 0 1]


In [45]:
print (x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 21.0 151100.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 30.0 151100.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 34.0 90000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 100000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 27.0 60000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 22.0 151100.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 24.0 151100.0]]


In [46]:
print (x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 700000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 34.0 52000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 25.0 200000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 34.0 80000.0]]


In [47]:
print (y_train)

[1 1 0 0 1 1 0 1 1]


In [48]:
print (y_test)

[0 1 0 0 0]


In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

Kode tersebut digunakan untuk menormalkan (menskalakan) data numerik agar memiliki skala yang sama.

- StandardScaler berfungsi mengubah data sehingga memiliki rata-rata 0 dan standar deviasi 1. Ini penting agar model machine learning tidak bias terhadap nilai yang terlalu besar.
- sc.fit_transform(x_train[:, 3:]) → menghitung rata-rata dan standar deviasi dari data training (kolom ke-3 ke atas), lalu langsung mengubah nilainya.
sc.transform(x_test[:, 3:]) → menggunakan perhitungan dari data training tadi untuk mengubah data testing (tanpa menghitung ulang).

In [50]:
print (x_train)

[[0.0 0.0 0.0 -0.35355339059327373 0.0 -0.3535533905932736
  2.828427124746189 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 -1.1254962578263243
  1.0679663633368157]
 [0.0 0.0 0.0 -0.35355339059327373 0.0 2.828427124746189
  -0.3535533905932736 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 -0.26544723061941616
  1.0679663633368157]
 [0.0 0.0 0.0 2.82842712474619 0.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 0.116796781472543
  -0.5840018594449422]
 [0.0 0.0 0.0 -0.35355339059327373 0.0 -0.3535533905932736
  -0.3535533905932736 2.82842712474619 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 1.6457728298403795
  -0.313630628220432]
 [1.0 0.0 0.0 -0.35355339059327373 0.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3

In [51]:
print (x_test)

[[0.0 0.0 0.0 -0.35355339059327373 0.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 1.0 -0.3535533905932738 0.6901627996104818
  15.908643245250186]
 [0.0 0.0 0.0 -0.35355339059327373 1.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 1.4546508237944
  -0.8814102137919035]
 [0.0 0.0 0.0 -0.35355339059327373 0.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 1.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 0.116796781472543
  -1.6114125380980815]
 [0.0 0.0 1.0 -0.35355339059327373 0.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 0.0 0.0 -0.35355339059327373
  -0.3535533905932738 0.0 -0.3535533905932738 -0.7432522457343651
  2.390081684024671]
 [0.0 0.0 0.0 -0.35355339059327373 0.0 -0.3535533905932736
  -0.3535533905932736 -0.35355339059327373 0.0 1.0 -0.35355339059327373